apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: websql
  annotations:
    maintainer: "Guru the Great"
    state: "In progress"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websql
  template:
    metadata:
      labels:
        app: websql
        pod: websql-sql
    spec:
      containers:
      - name: sqlcont
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlpw
              key: password
        volumeMounts:
        - name: timezonehost
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: timezonehost
        hostPath:
          path: /etc/localtime
