apiVersion: v1
kind: Service
metadata:
  name: webrockserver
  labels:
    app: websql
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32133
    protocol: TCP
  selector:
    pod: websql-web
